name:                json-parse
version:             0.1.0.0
github:              "githubuser/json-parse"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         json-parse

default-extensions:
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- ViewPatterns

dependencies:
- attoparsec
- base >= 4.7 && < 5
- bytestring
- containers
- scientific
- text
- vector

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror

tests:
  json-parse-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - json-parse
    - hspec
